### PR TITLE
In the client has been added the ability to specify the settings.

### PR DESCRIPTION
**Pull request by Arekusei**
Sometimes need pass parameters for http client.
Eg. 
* Disable https verification.
* Specify timeout.

### CODE REVIEW

**Comment by zyberspace** [comment]
Hi!
So first of all i agree that having an argument for client options is a good idea.

However i don't think your additional changes regarding the custom http client are necessary. If someone needs to use another http client than guzzle he should just extend the class and override the `__construct()` method.
Adding a `setHttpClient()` just adds unneeded complexity. Here is the flow with your pull requests if someone wants to change the http client:
```php
$steamClient = new \Zyberspace\SteamWebApi\Client($apiKey, [
    'myOption' => 'optionValue'
]);
$steamClient->setHttpClient($myCustomClient); //Completely ignores the previous set options

//And now we can do api stuff
```
So first i *initialize* the api client and **then**, **after** initializing it, i change the http client. I think there exists a pattern for this but it's a stupid flow, sry.

So how about we move the guzzle client creation into it's own method that then just needs to be overridden by a new class that extends from the existing one? Something like this:
```php
class Client {
    ....

    public function __construct($apiKey, $guzzleOptions = array())
    {
        $this->_apiKey = $apiKey;
        $this->_guzzleClient = $this->_createGuzzleClient($guzzleOptions);
    }

    protected function _createGuzzleClient($guzzleOptions) {
        return new \GuzzleHttp\Client(array_merge(
            array('base_uri' => self::BASE_URL),
            $guzzleOptions
        ));
    }

    ...
}

/*
  ---------------------
  Then in your project:
  ---------------------
*/
class MyCustomSteamApiClient extends Client {
    //Only method that needs to be overridden
    protected function _createGuzzleClient($guzzleOptions) {
        return new MyCustomGuzzleClient($guzzleOptions);
    }
}
```

This way the the majority of users still have a simple Client class and the (i think) minority that needs their own custom guzzle like client can use it with a little bit of work too.

**Comment by Arekusei** [comment]
Hi!
You're right.
But also we can do:
```php
class Client
{
    //....
    public function __construct($apiKey, \Closure $httpClientFactory = null)
    {
        $this->_apiKey = $apiKey;

        $httpOptions = array('base_uri' => self::BASE_URL);
        $this->_httpClient = $httpClientFactory ? $httpClientFactory($httpOptions) : new \GuzzleHttp\Client($httpOptions);
    }
    //...
}
```
or
```php
class Client
{
    //....

    /**
     * @var \Closure
     */
    private $_httpClientFactory;
    /**
     * @var \GuzzleHttp\ClientInterface
     */
    private $_httpClient;

    public function __construct($apiKey)
    {
        $this->_apiKey = $apiKey;
    }

    public function setHttpClientFactory(\Closure $factory)
    {
        $this->_httpClientFactory = $factory;
    }

    protected function getHttpClient()
    {
        if (!$this->_httpClient) {
            if ($this->_httpClientFactory) {
                $factory = $this->_httpClientFactory
                $this->_httpClient = $factory(array('base_uri' => self::BASE_URL));
            } else {
                $this->_httpClient = new \GuzzleHttp\Client(array('base_uri' => self::BASE_URL));
            }
        }

        return $this->_httpClient;
    }

    //...
}
```
Or 
```php
class Client
{
    //....
    public function __construct($apiKey, $clientOptions = array())
    {
        $this->_apiKey = $apiKey;

        $this->_httpClient = $this->createHttpClient(array_merge(array('base_uri' => self::BASE_URL), $clientOptions));
    }

    /**
     * @param array $options
     * @return \GuzzleHttp\ClientInterface
     */
    protected function createHttpClient(array $options)
    {
        return new \GuzzleHttp\Client($options);
    }
    //...
}


class CustomClient extends Client
{
    /**
     * @inheritdoc
     */
    protected function createHttpClient(array $options)
    {
        //...
    }
}
```

I think we don't need to use guzzle in method names.
What do you think about all this? 
I can change my pull request when we will chose a solution. )

**Comment by zyberspace** [comment]
My problem with naming it `$clientOptions` is that it could cause some confusion because `$clientOptions` could also mean that those are options for the steam web api client instead of the guzzle / custom http client.

But maybe we can first clarify for what you (and others) actually need to pass options / set your own http client. From my view the only reason to do that would be to have something like an api request cache, running the client behind a proxy or some exotic network setup.

Both, the custom network setup and the request cache, would probably require you to set your own http client either so your first solution would work perfectly.

What i am saying is if you only need to change the options when you also need a custom http client, there is no need to be able to pass the options separately because you can just pass your already set up  http client:
```php
$apiClient = new Client($apiKey, new MyCustomHttpClient($myOptions));
```

**Comment by Rodion15** [comment]
Guys, can you show an example of how to work with authorization?

**Pull request closed without merging**
